NumPy Neden Kullanılır?
=======================

NumPy, bilimsel hesaplama ve veri analizi için Python'da yaygın olarak kullanılan güçlü bir kütüphanedir. Temeli, 2005 yılında Travis Oliphant tarafından geliştirilmiş ve Numerical Python ifadesinden türetilmiştir. 

- **Çok Boyutlu Diziler (ndarray):** NumPy, büyük ve çok boyutlu dizilerle çalışmayı sağlar.
- **Performans:** Python listelerine göre çok daha hızlı matematiksel işlemler yapılabilir.
- **Bellek Verimliliği:** Aynı veri üzerinde daha az bellek kullanır.
- **Kapsamlı Fonksiyonlar:** İstatistiksel ve matematiksel pek çok fonksiyonu içerir.
- **Ekosistem:** Pandas, SciPy, scikit-learn gibi popüler kütüphanelerin temelini oluşturur.

Yani, veri biliminde ve bilimsel hesaplamalarda hem hız hem de verimlilik sağladığı için NumPy kullanılır.

NumPy Dizileri ve Python Listeleri Arasındaki Farklar
=====================================================

NumPy dizileri (`ndarray`) ile Python'ın standart listeleri arasında bazı önemli farklar vardır:

- **Veri Tipi (Homojenlik):** NumPy dizilerinde tüm elemanlar aynı veri türünde olmak zorundadır. Python listelerinde ise farklı veri türleri bir arada bulunabilir.
- **Hız ve Performans:** NumPy dizileri, büyük miktarda veriyle çalışırken Python listelerine göre çok daha hızlıdır. Bunun nedeni, NumPy'nin düşük seviyeli optimizasyonlar kullanmasıdır.
- **Bellek Kullanımı:** NumPy dizileri verileri aralıksız bir blokta depolayarak daha az bellek kullanır. Python listelerinde ise her eleman kendi başına bir nesnedir ve daha fazla bellek gerektirir.
- **Vektörel İşlemler:** NumPy dizileri ile toplama, çıkarma, çarpma gibi işlemler doğrudan tüm diziye uygulanabilir. Python listelerinde döngü veya list comprehension gerekir.
- **Çok Boyutluluk:** NumPy ile kolayca iki veya daha fazla boyutlu diziler oluşturulabilir. Python listelerinde ise iç içe listeler kullanmak gerekir ve bu daha karmaşıktır.
- **Gelişmiş Fonksiyonlar:** NumPy, istatistiksel ve matematiksel işlemler için birçok yerleşik fonksiyon sunar. Python listeleri ise bu tür işlemleri doğrudan desteklemez.

Sonuç olarak, özellikle büyük ve sayısal veriyle çalışırken NumPy dizileri genellikle Python listelerine göre daha avantajlıdır.

In [2]:
import numpy as np # numpy kütüphanesini np olarak kısaltıyoruz

In [ ]:
# Klasik yöntem
a = [1,2,3,4,5]
b = [2,3,4,5,6]

ab = []
for i in range(len(a)):
    ab.append(a[i] * b[i])

print(ab)

[2, 6, 12, 20, 30]


In [ ]:
c = np.array([1,2,3,4,5])
d = np.array([2,3,4,5,6])
cd = c * d
print(cd)



[ 2  6 12 20 30]


## Numpy Array Oluşturma
NumPy'da veri saklamak ve üzerinde işlemler yapmak için en temel yapı `ndarray` yani çok boyutlu dizilerdir. Bir NumPy dizisi oluşturmak için genellikle `np.array()` fonksiyonu kullanılır. Python listesi gibi temel veri yapılarını NumPy dizisine dönüştürebiliriz. NumPy dizileri sayısal işlemler için optimize edilmiştir ve farklı veri tiplerinde büyük ve çok boyutlu veri setlerini kolayca saklamamıza olanak tanır.

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
type(np.array([1,2,3,4,5]))


numpy.ndarray

In [7]:
np.zeros(10) # np.zeros() fonksiyonu, belirtilen boyutta sıfırlardan oluşan bir dizi oluşturur.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.random.randint(10,100,5) # np.random.randint() fonksiyonu, belirtilen aralıkta rastgele tamsayılar içeren bir dizi oluşturur.

array([15, 97, 69, 16, 25])

In [ ]:
np.random.normal(10,4,(3,4)) # np.random.normal() fonksiyonu, belirtilen ortalama ve standart sapma değerlerine sahip normal dağılımlı sayılar içeren bir dizi oluşturur. Parametreler:
# - ortalama: Normal dağılımın ortalama değeri
# - standart_sapma: Normal dağılımın standart sapma değeri
# - boyut: Oluşturulacak dizinin boyutu (örneğin (3,4) yaparsak 3x4 boyutunda bir dizi oluşturur)



array([[12.08404482, 10.5388419 ,  3.71614767, 11.90681937],
       [ 6.01635051,  1.49272656, 12.68287448, 18.74892112],
       [ 9.33490381,  7.45513729,  8.71462434,  8.45880589]])

Numpy array'lerin (ndarray) başlıca özellikleri şunlardır:

- **Boyut Sayısı (ndim):** Dizinin kaç boyutlu olduğunu gösterir.
- **Şekil (shape):** Dizinin her bir boyuttaki eleman sayısını gösteren bir tuple’dır.
- **Veri Tipi (dtype):** Dizideki elemanların veri tipini belirtir.
- **Toplam Eleman Sayısı (size):** Dizideki toplam eleman sayısıdır.
- **Eleman Başına Bellek Boyutu (itemsize):** Her bir elemanın bayt cinsinden kapladığı alanı gösterir.
- **Verilerin Saklandığı Bellek Tipi (data):** Verilerin tam olarak bellekte nerede saklandığına dair bilgi verir.

Bu özellikler sayesinde Numpy dizileriyle çalışmak hem kullanışlı hem de esnektir.

In [11]:
a = np.random.randint(10, size=5)
print(a)

[0 8 5 6 2]


In [12]:
print("Boyut sayısı:", a.ndim)
print("Şekil:", a.shape)
print("Veri tipi:", a.dtype)
print("Toplam eleman sayısı:", a.size)
print("Eleman başına bellek boyutu:", a.itemsize)
print("Verilerin saklandığı bellek tipi:", a.data)


Boyut sayısı: 1
Şekil: (5,)
Veri tipi: int64
Toplam eleman sayısı: 5
Eleman başına bellek boyutu: 8
Verilerin saklandığı bellek tipi: <memory at 0x108bbfdc0>


### Reshaping (Yeniden Şekillendirme)

Numpy dizileri üzerinde `reshape` metodu ile dizinin eleman sayısını değiştirmeden yeni bir boyutlandırma yapılabilir. Yani, toplam eleman sayısı aynı kalacak şekilde dizi farklı satır ve sütunlara ayrılabilir. Örneğin, bir boyutlu 12 elemanlı bir dizi, `reshape(3, 4)` ile 3 satır 4 sütunluk iki boyutlu bir diziye dönüştürülebilir. Dizinin toplam eleman sayısı ile yeni şeklin çarpımı aynı olmalıdır, aksi halde hata alınır.

`reshape` sayesinde verilerin formatı ihtiyaçlara göre kolayca değiştirilebilir ve çok boyutlu işlemler daha pratik hale gelir.

In [14]:
a = np.random.randint(1, 9, size=9)
a.reshape(3,3)



array([[5, 1, 5],
       [2, 1, 3],
       [5, 4, 1]])

### Numpy'da İndeks Seçimi

Numpy dizilerinde indeksleme, dizilerdeki belirli elemanlara veya dilimlere erişmek için kullanılır. Tek boyutlu dizilerde, tıpkı Python listelerinde olduğu gibi köşeli parantezlerle bir elemana ulaşılır. Örneğin, `a[0]` ilk elemana erişir. Negatif indeksler ile sondan başlanarak erişim sağlanabilir (`a[-1]` son elemanı döndürür).

Çok boyutlu dizilerde ise virgülle ayrılmış çoklu indeksler kullanılır. Örneğin, iki boyutlu bir dizi olan `b` için `b[1, 2]` ifadesi 1. satır ve 2. sütundaki elemana erişir. Ayrıca dilimleme (slicing) ile birden fazla elemana da erişmek mümkündür: `b[:, 0]` tüm satırların ilk sütunundaki elemanları döndürür. Benzer şekilde, `b[1, :]` ikinci satırdaki tüm elemanları verir.

Hem temel indeksleme hem de dilimleme yöntemleri ile, Numpy dizilerinde eleman seçimini esnek ve hızlı bir şekilde yapmak mümkündür.

In [ ]:
a = np.random.randint(10, size=10)
a[0]

np.int64(4)

In [17]:
a[0:5]

array([4, 5, 1, 9, 1])

In [18]:
a[0] = 999

In [ ]:
m = np.random.randint(10, size=(3,5))

In [20]:
m[0,0]

np.int64(1)

In [22]:
m[2,3] = 999
m[2,3]
m

array([[999,   6,   5,   8,   6],
       [  2,   9,   2,   2,   0],
       [  2,   8,   0, 999,   5]])

In [23]:
m[2,3] = 2.9
m[2,3]

np.int64(2)

In [24]:
m[:, 0] # tüm satırların ilk sütunundaki elemanları döndürür

array([999,   2,   2])

In [25]:
m[1,:] # tüm sütunundaki elemanları döndürür

array([2, 9, 2, 2, 0])

In [26]:
m[0:2, 0:3] # 0. ve 1. satırların 0. 1. ve 2. sütunlarındaki elemanları döndürür

array([[999,   6,   5],
       [  2,   9,   2]])

### Fancy Index nedir?

Fancy index (veya fancy indexing), NumPy dizileri üzerinde birden fazla elemanı, bu elemanların indekslerini bir dizi veya liste şeklinde belirterek seçmeye olanak tanıyan bir indeksleme yöntemidir. Fancy index ile dizinin herhangi bir sıra veya konumundaki elemanlar doğrudan elde edilebilir. Örneğin, bir diziden [0, 3, 4] indekslerindeki elemanları aynı anda almak için kullanılabilir. Bu yöntemle, birden fazla eleman kolayca ve esnek bir şekilde seçilebilir.

In [27]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [28]:
v[[0,3,4]]

array([ 0,  9, 12])

### NumPy'da Koşullu ve Matematiksel İşlemler

NumPy dizileri üzerinde koşullu ifadeler ve matematiksel işlemler oldukça kolay ve hızlı bir şekilde uygulanabilir. Koşullu işlemler sayesinde dizilerde belirli şartlara uyan elemanlar kolayca seçilebilir veya bu elemanlar üzerinde farklı işlemler yapılabilir. Ayrıca, NumPy'nin sunduğu matematiksel fonksiyonlar ile toplama, çıkarma, çarpma, bölme gibi temel işlemlerin yanı sıra, karesini alma, karekök, logaritma ve üstel fonksiyonlar gibi daha karmaşık matematiksel işlemlerin tümü vektörel olarak ve çok hızlı bir biçimde gerçekleştirilebilir.

**Koşullu İşlemler:**

Bir NumPy dizisinde koşullu işlem yapmak için, doğrudan mantıksal bir ifade kullanılabilir ve bu ifade sonucunda orijinal diziyle aynı boyutta bir bool dizisi elde edilir. Bu bool dizisi, elemanların koşulu sağlayıp sağlamadığını gösterir. Sonrasında, bu koşul kullanılarak ilgili elemanlara kolayca erişilebilir.

Örneğin:

```python
import numpy as np

a = np.array([10, 15, 20, 25, 30])
a > 20
# array([False, False, False,  True,  True])
a[a > 20]
# array([25, 30])
```

**Matematiksel İşlemler:**

NumPy dizilerinin tüm elemanlarını doğrudan matematiksel işlemlere sokabilirsiniz. İşte bazı temel örnekler:

```python
b = np.array([1, 2, 3, 4])
b + 5         # array([6, 7, 8, 9])
b * 2         # array([2, 4, 6, 8])
np.square(b)  # array([ 1,  4,  9, 16])
np.sqrt(b)    # array([1.        , 1.41421356, 1.73205081, 2.        ])
np.log(b)     # array([0.        , 0.69314718, 1.09861229, 1.38629436])
```

Bu işlemler vektörel olarak uygulandığı için, Python'daki klasik döngülere göre çok daha hızlıdır. Ayrıca, aynı anda tüm dizi üzerinde işlemler yapılırken kodun okunabilirliği de artar.

NumPy ile koşullu ve matematiksel işlemler, veri analizinde ve bilimsel hesaplamalarda büyük kolaylık ve hız sağlar.

In [31]:
v = np.array([1,2,3,4,5])
ab = []
for i in v:
    if i < 3:
        ab.append(i)
ab


[np.int64(1), np.int64(2)]

In [32]:
v[v < 3]


array([1, 2])

In [33]:
v[v > 3]

array([4, 5])

In [34]:
v[v == 3]

array([3])

In [35]:
v[v != 3]

array([1, 2, 4, 5])

In [36]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [37]:
v * 5 / 10 

array([0.5, 1. , 1.5, 2. , 2.5])

In [38]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [39]:
v - 1

array([0, 1, 2, 3, 4])

In [40]:
np.subtract(v,1) # v'nin her elemanından 1 çıkarır

array([0, 1, 2, 3, 4])

In [41]:
np.add(v,1) # v'nin her elemanına 1 ekler

array([2, 3, 4, 5, 6])

In [42]:
np.mean(v) # v'nin ortalamasını hesaplar

np.float64(3.0)

In [43]:
np.sum(v) # v'nin tüm elemanlarının toplamını hesaplar

np.int64(15)

In [44]:
np.min(v) # v'nin en küçük elemanını döndürür

np.int64(1)

In [45]:
np.max(v) # v'nin en büyük elemanını döndürür

np.int64(5)

In [46]:
np.var(v) # v'nin varyansını hesaplar

np.float64(2.0)

In [ ]:
## Numpy ile Denklem Çözümü

a = np.array([[5,1], [1,3]])
b = np.array([12,10])
np.linalg.solve(a,b) 

array([1.85714286, 2.71428571])